server :
    port : 80
spring :
    thymeleaf :
        prefix : thyme/
        suffix : .html
        cache : false
        
    datasource :
        driver-class-name : org.mariadb.jdbc.Driver
        url : jdbc:mariadb://localhost:3306/fc_db?allowMultiQueries=true
        username : fassion
        password : 1234
        
        
        
mybatis :
    type-aliases-package : fc.db
            
            

            
